language: ruby
sudo: false
rvm:
- 1.9.3
- 2.0
- 2.1
- ruby-head
- jruby-19mode
- jruby-head
- rbx-2
matrix:
  allow_failures:
  - rvm:
      - rbx-2
      - jruby-19mode
      - jruby-head
addons:
  code_climate:
    repo_token: 4e8013e9105e3dd8153da54825ce8fab58c7408dce36fa351ef35c51bb9b0b05
notifications:
  slack:
    secure: awgcYPnPALqyAn3H58d+qzQYezzEyuqr71GmU9AsXuOa3sGM1JVqmUOqgoXeykBcV8EV5DEO+65fCkc+GnBxyPjnyYyvzW7VEcj3xQdxyVgn9fK0a76Mp+ywoWOPG7t4Z8dIK3PCT12QO+XgGWiLA9YG10eRtGRRD1V2PCKv41Y=
